version: "3.8"

services:
    api-gdt:
        build: .
        ports:
            - 8080:83
        restart: unless-stopped
        tty: true
        dns:
            - 8.8.8.8
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        environment:
            DB_CONNECTION: "{{env ('DB_CONNECTION')}}"
            DB_HOST: "{{ env('DB_HOST') }}"
            DB_PORT: "{{env('DB_PORT')}}"
            DB_DATABASE: "{{ env('DB_DATABASE') }}"
            DB_USERNAME: "{{ env('DB_USERNAME') }}"
            DB_PASSWORD: "{{ env('DB_PASSWORD') }}"

networks:
    app-network:
        driver: bridge
